def x = (mul 11 (sum 5 6))
def y = (mul 34 (sum 5 (foo-bar 4 5)))
def m n k
con f = (and on off)
con number255 = 0xff

(console/log (x) -> (div $ 8))
(foo-bar)

export def man-man
    def second-level
        throw 0
    end
    def something = 5
end

def cool = (x) -> (div $ 2) -> (z) ->
    (mul $ 5) -> (foo-bar) -> (go)

(console/log 2)

async delay time
    return new (Promise [ res => (setTimeout res time) ])
end

await (delay 5000)